### ISSUE TITLE
Erls 1000hz presets

### ISSUE THREAD

**Issue by limonspb** [betaflight/firmware-presets#361]
Upload logs here

**Comment by lowefpv** [comment]
hopefully this is ok a i did get hot motors using 500hz peset i normaly dont during flight

**Comment by lowefpv** [comment]
[btfl_all.bbl.csv](https://github.com/betaflight/firmware-presets/files/10829254/btfl_all.bbl.csv)

**Comment by lowefpv** [comment]
![btfl_all_bbl csv-20230224-224110](https://user-images.githubusercontent.com/95387092/221310181-baef5a29-df77-4b8a-bbc9-b31f8dc4171f.png)

**Comment by lowefpv** [comment]
so ive sill not managed to get it to upload even after changing the name so ive had to upload it to we transfer if you visit this link you will get the download hopefully this helps many thanks in advance for all your help and hard work  
   link     https://we.tl/t-XDH1uE2S5X

**Comment by limonspb** [comment]
> so ive sill not managed to get it to upload even after changing the name so ive had to upload it to we transfer if you visit this link you will get the download hopefully this helps many thanks in advance for all your help and hard work link https://we.tl/t-XDH1uE2S5X

@sugaarK

**Comment by ctzsnooze** [comment]
To accurately analyse smoothing of something that steps at 1,000hz requires that we sample quite a lot faster.  This log was at 2kHz, and that leads to aliasing artefacts.  Could I suggest disabling as many logging items as possible, and logging at the full 8k?  All we need is RC command, set point, and feedforward.

Also it's best to test on the bench top with zero expo so that the setpoint and RC command curves overlap in the log, with full stick travel inputs. 

Using the log we have, it looks like the RC smoothing value is OK.  It is set to 25, resulting in a PT3 cutoff at 430Hz.
This image shows the smoothing looks OK, but there is sampling aliasing, and the precision of the measurement of setpoint is a bit limiting.  If the log has high-resolution setpoint it is better.  We expect steps in RC command, but setpoint should be smooth.  Overall, setpoint smoothing is sufficient.  In part this is because at such a high link speed, the amount of change from one step to the next is always going to be small, so the smoothing requirement isn't massive since the size of any steps is small to start with.

![Screen Shot 2023-02-26 at 13 42 17](https://user-images.githubusercontent.com/11737748/221389456-bc8424ad-836b-4225-86c7-30bad169a072.jpg)

Feedforward is an entirely different situation.  There is quite a lot of variability in feedforward.  This is because the resolution of the RC signal is not so great, especially when the sticks are not moving super fast.  There is a limit to how accurately the change in position can be measured, from packet to packet, at such high rates.

This image shows feedforward, P and RC command all at the same scale factor.
Note that there is quite a lot more noise on feedforward than on P itself (and P carries gyro noise and setpoint noise).
The noise on FF is quite spiky; those spikes align with steps in the RC Command signal

![Screen Shot 2023-02-26 at 13 54 27](https://user-images.githubusercontent.com/11737748/221389767-6f1a5a36-1f74-4ade-a64b-4909bd78a946.jpg)

Clearly this setup needs stronger feedforward smoothing than the 430hz given with auto smoothing of 25.

Could I suggest making another log at 4kHz, disabling as much other unnecessary stuff from the log, and trying a manual setpoint value of 400 and a manual feedforward value of 200, and then make a second log with the manual feedforward value of 100?

**Comment by limonspb** [comment]
Racing preset for 1000Hz was created and merged. Thanks to @ctzsnooze  and @sugaarK

**Comment by Wikiwix** [comment]
For anyone curious: The change came with https://github.com/betaflight/firmware-presets/pull/362 and is not labelled with ExpressLRS

**Comment by sugaarK** [comment]
> For anyone curious: The change came with #362 and is not labelled with ExpressLRS

Yeah we made a basic 1000hz preset. It’s found in all my karate presets now
